### ISSUE TITLE
Sprint 1

### ISSUE THREAD

**Issue by wsor4035** [minetest/minetest_docs#38]
As proposed in the [IRC channel](https://irc.minetest.net/minetest-docs/2022-08-15#i_6007748) and suggested by benrob, going to start a 2 week sprint for getting some docs done.

* [x] before 8/19/2022 - pick a topic you will be covering
* [ ] 8/19/2022 ~~or before~~ to 8/26/2022 - work on the doc, get it ready for review
* [ ] 8/26/2022 to 9/2/2022 - get your PR reviewed, and review someone else's

List of topics taken:

* [ ] @benrob0329: [`AreaStore`](https://github.com/minetest/minetest/blob/f7311e0d97cb89bcb197a3e6b89e039151bb510f/src/script/lua_api/l_areastore.cpp)
* [ ] @wsor4035: HTTP API
* [x] @GreenXenith: [`ItemStack`](https://github.com/minetest/minetest/blob/5.6.0/doc/lua_api.txt#L6640-L6707)
* [x] @appgurueu: MetaDataRef etc.
* [ ] @ExeVirus: Sound
* [ ] @rollerozxa: [`Settings`](https://github.com/minetest/minetest/blob/5.6.0/doc/lua_api.txt#L7443)

**Comment by GreenXenith** [comment]
[`ItemStack`](https://github.com/minetest/minetest/blob/5.6.0/doc/lua_api.txt#L6640-L6707)

**Comment by rollerozxa** [comment]
[`Settings`](https://github.com/minetest/minetest/blob/5.6.0/doc/lua_api.txt#L7443) (which assumedly would also include `minetest.settings`)

**Comment by appgurueu** [comment]
`MetaDataRef` and all subclasses (`StorageRef`, `NodeMetaRef`, `ItemStackMetaRef`,
and `PlayerMetaRef`)

**Comment by ExeVirus** [comment]
```mermaid
graph LR;
    sound["sound and music backend"]
    ExeVirus-->|want's to document|sound
    sound <--> loading
    sound <--> randomization
    file["supported file types"]
    sound <--> file
    API["sound lua API"]
    sound <--> API
```

**Comment by appgurueu** [comment]
https://github.com/minetest/minetest_docs/pull/40

**Comment by benrob0329** [comment]
[`Areastore`](https://github.com/minetest/minetest/blob/f7311e0d97cb89bcb197a3e6b89e039151bb510f/src/script/lua_api/l_areastore.cpp)

**Comment by appgurueu** [comment]
For the record (and if we choose to organize future sprints this way): We can edit your issue, so there's no need for you to update or us to comment.

**Comment by wsor4035** [comment]
I am aware of editing, but that iirc doesnt notify people while a comment does.

**Comment by appgurueu** [comment]
Reminder to tick the checkboxes of the [mega tracker](https://github.com/minetest/minetest_docs/issues/16) as your PRs get merged.
